apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: csantanapr/app-rates
        imagePullPolicy: Always
        ports:
        - containerPort: 8080